# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Tomislav Novoselec
tagline:          'Yada yada'
description:      'A blog about everything'
url:              http://tnovoselec.github.io
baseurl:          /

author:
  name:           'Tomislav Novoselec'
  url:            tnovoselec.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tnovoselec.github.io
